"""Publiczne API pakietu `luca_processing`."""

from luca_processing.detector_interfaces import BaseDetector, DetectorBackendError, DetectorConfig
from luca_processing.detection_profiles import available_detection_profiles, resolve_detection_profile
from luca_processing.detector_registry import available_detector_names, get_default_params, get_detector_class
from luca_processing.detectors import (
    BrightnessDetector,
    COLOR_PRESETS,
    ColorDetector,
    DetectionPersistenceFilter,
    TemporalMaskFilter,
    build_mask,
    contour_to_detection,
    detect_spots,
    detect_spots_with_config,
    ensure_odd,
    get_default_params_for_mode,
    parse_hsv_pair,
    parse_roi,
)
from luca_processing.postprocess import KalmanConfig, apply_kalman_to_points, smooth_xy_with_config
from luca_processing.world_projection import (
    PnPPoseEstimateResult,
    ProjectionStageStatus,
    WorldCoordinateFilter,
    WorldCoordinateFilterConfig,
    WorldProjectionResult,
    estimate_pnp_pose,
    estimate_pnp_pose_with_status,
    parse_point_series,
    pixel_to_world_on_plane,
    pixel_to_world_on_plane_with_status,
    format_world_projection_diagnostics,
    world_projection_error_causes_from_codes,
    world_projection_reason_from_codes,
)

# Lista symboli wspieranych jako stabilny kontrakt dla pozostałych pakietów.
__all__ = [
    "BaseDetector",
    "DetectorBackendError",
    "DetectorConfig",
    "available_detector_names",
    "available_detection_profiles",
    "get_default_params",
    "get_detector_class",
    "resolve_detection_profile",
    "BrightnessDetector",
    "COLOR_PRESETS",
    "ColorDetector",
    "DetectionPersistenceFilter",
    "TemporalMaskFilter",
    "build_mask",
    "contour_to_detection",
    "detect_spots",
    "detect_spots_with_config",
    "ensure_odd",
    "get_default_params_for_mode",
    "parse_hsv_pair",
    "parse_roi",
    "KalmanConfig",
    "apply_kalman_to_points",
    "smooth_xy_with_config",
    "parse_point_series",
    "ProjectionStageStatus",
    "PnPPoseEstimateResult",
    "WorldCoordinateFilterConfig",
    "WorldCoordinateFilter",
    "WorldProjectionResult",
    "estimate_pnp_pose",
    "estimate_pnp_pose_with_status",
    "pixel_to_world_on_plane",
    "pixel_to_world_on_plane_with_status",
    "format_world_projection_diagnostics",
    "world_projection_error_causes_from_codes",
    "world_projection_reason_from_codes",
]
